//Block of Code That Calculates The RPM and Vehicle Speed of an Electric Vehicle (Noise-proof)
//with a HALL Effect and a Nucleo-F446RE.
//You have to initialize two timers as a Counter and Timeout Timer. As a Counter Timer i use htim2
//that has 2^32 -1 Max Period. with a Prescaler of 1280 -1 (And the HCLK == 128). That way my Timer
//clicks every 10us
//The other Timer is such that it produces a Timeout when RPM are stable for a period of time. Im
//both Timers , Enable Interrupts and preload while setting Trigger Evet Selection to "Update Event"
//The Pins that I have connected the Hall Effects sensors are both internally and externally Pulled-Up
//and are registered as external Interrupts with falling edge trigger.

#include "stm32f4xx_hal.h"

//Structure For the Hall Effect Data
struct hallEffectSensor{
	TIM_HandleTypeDef* counter; // 32-bit Timer
	TIM_HandleTypeDef* timeOutTimer; //Generic Timer
	uint32_t time_now;
	uint32_t time_before;
	uint16_t rpm; //measured in rpms
	float vehicle_speed;//measured in m/min
	float radius;//measured in m
	float tuner;//Variable to tune the rpms. Set Default to 1
	uint8_t isReady;//Flag that is updated when the signal of the hall Effect Sensor is pulled Down

};

//Main Function
void hf_calculator(struct hallEffectSensor hf){
	  if(hf.isReady==1){
		  hf.isReady=0;
		  hf.time_now = __HAL_TIM_GET_COUNTER(hf.counter);
		  //hf.rpm = pi*100000/(hf.time_now-hf.time_before); // Enable this if HclkFrequency/TimerPreScaler = 100000
		  hf.rpm = pi*(HAL_RCC_GetHCLKFreq()/(hf.counter->Init.Prescaler+1))/(hf.time_now-hf.time_before);//Generic but slower

		  hf.vehicle_speed = 2*pi*hf.radius*hf.rpm;
		  hf.rpm = gear_ratio*(rpm_conv*hf.rpm)*hf.tuner;
		  hf.time_before = hf.time_now;
		  hf.timeOutTimer->Instance->CNT = 0;
	  }
	  return;
}
int main(void){
  //Functions that are autoGenerated from Stm32CubeMx
  HAL_Init();
  SystemClock_Config();
  MX_GPIO_Init();
  MX_TIM2_Init();
  MX_TIM6_Init();
  MX_TIM7_Init();



}
